////////////////////////////////////////////////////////////////////////////////
//
// RAGE1 - Retro Adventure Game Engine, release 1
// (c) Copyright 2020 Jorge Gonzalez Villalonga <jorgegv@daikon.es>
//
// This code is published under a GNU GPL license version 3 or later.  See
// LICENSE file in the distribution for details.
//
////////////////////////////////////////////////////////////////////////////////

#ifndef _GFX_JSP_H
#define _GFX_JSP_H

#include <stdint.h>
#include <jsp.h>

//--- Types ---
typedef struct jsp_sprite_s      gfx_sprite_t;
typedef struct jsp_rect          gfx_rect_t;
typedef struct jsp_print_ctx     gfx_print_ctx_t;
typedef uint8_t                  gfx_attr_t;

// Pixel coordinate widths (Phase G4 — gfx.md §G4-1).
// On ZX backends 256x192 fits in a byte, so we stay at uint8_t to avoid the
// 16-bit codegen cost.  The CPC backend (Phase G7) will redefine these as
// uint16_t for 320x200 and future ZX Next Layer-2 backends likewise for
// 320x256 / 640x256.  Engine code must use these typedefs at every site that
// holds an integer screen pixel coordinate so the same source compiles on
// both byte- and word-coordinate backends.
typedef uint8_t                  gfx_xpos_t;
typedef uint8_t                  gfx_ypos_t;

// Tile / glyph identifier (Phase G6 — gfx.md §G6-1).
// On JSP a tile id is the polysemic uint16_t passed to jsp_tile_put(): values
// < 256 are UDG character codes, values >= 256 are 16-bit tile addresses.  Engine
// code must use this typedef for the tile argument of gfx_tile_put() so the same
// source compiles on the CPC backend (Phase G7), where the id is a backend-internal
// tile-cache index instead.
typedef uint16_t                 gfx_tile_id_t;

//--- Constants ---
#define GFX_CLEAR_TILE              JSP_RFLAG_TILE
#define GFX_CLEAR_COLOUR            JSP_RFLAG_COLOUR
#define GFX_PSS_INVALIDATE          0x00    // unused in JSP backend
#define GFX_PRINT_CTX_INIT(a,at)    JSP_PRINT_CTX_INIT((a),(at))

// Screen geometry in cells (Phase G5 — gfx.md §G5-1).
// JSP renders the standard ZX Spectrum 32x24 character grid.  The CPC backend
// (Phase G7) will redefine these (mode-1: 40x25), and ZX Next Layer-2 likewise.
// Engine code must use these constants at every site that holds a screen-grid
// dimension so the same source compiles unchanged on backends with a different
// character-cell geometry.
#define GFX_SCREEN_COLS             32
#define GFX_SCREEN_ROWS             24

//--- Attribute layer (ZX-only — inert on CPC, see gfx.md §2.1) ---
// ZX colour indices 0..7 (match arch/spectrum.h INK_*/PAPER_* numeric values)
#define GFX_BLACK                   0
#define GFX_BLUE                    1
#define GFX_RED                     2
#define GFX_MAGENTA                 3
#define GFX_GREEN                   4
#define GFX_CYAN                    5
#define GFX_YELLOW                  6
#define GFX_WHITE                   7
// Pack ink/paper/bright/flash into the standard ZX attribute byte
#define GFX_ATTR(ink,paper,bright,flash) \
    ( (uint8_t)( ((flash) << 7) | ((bright) << 6) | ((paper) << 3) | (ink) ) )
// Default background attribute (per-game value generated by datagen into DEFAULT_BG_ATTR)
#define GFX_DEFAULT_BG_ATTR         DEFAULT_BG_ATTR

//--- Initialization ---
// gfx_init() is a real function defined in gfx_jsp.c
#define gfx_invalidate(rect)                jsp_invalidate_rect(rect)
#define gfx_update()                        jsp_redraw()
// gfx_set_border() — border colour is consumed on every backend (CPC too).
// On ZX it is a Spectrum colour 0..7; the backend wraps zx_border().
#define gfx_set_border(color)               zx_border((color))

//--- Sprite lifecycle ---
// gfx_sprite_create() is a real function defined in gfx_jsp.c
#define gfx_sprite_destroy(s)               jsp_sprite_free(s)
// gfx_sprite_set_color() is a real function defined in gfx_jsp.c
#define gfx_sprite_set_threshold(s,xt,yt)   /* no-op: JSP has no threshold concept */

//--- Sprite movement ---
#define gfx_sprite_move_pixel(s,clip,fr,x,y) \
    gfx_jsp_move_sprite_clipped((s),(clip),(fr),(x),(y))
#define gfx_sprite_move_cell(s,clip,fr,r,c) \
    gfx_jsp_move_sprite_clipped((s),(clip),(fr),(c)*8,(r)*8)

// Park a sprite off-screen (Phase G5 — gfx.md §G5-4).  The parking row is a
// backend-internal detail: JSP parks at row 24 (one row below the visible 24-row
// grid), column 0.  Engine code never references the parking row directly; it
// calls gfx_sprite_park() — a single out-of-line __z88dk_fastcall function whose
// body lives in sprite.c — so each backend can choose its own off-screen slot.
#define GFX_PARK_ROW                        24
#define GFX_PARK_COL                        0

//--- Sprite query ---
#define gfx_sprite_get_row(s)               ((s)->ypos / 8)
#define gfx_sprite_get_col(s)               ((s)->xpos / 8)
#define gfx_sprite_get_width(s)             ((s)->cols)
#define gfx_sprite_get_height(s)            ((s)->rows)

//--- Tile drawing ---
#define gfx_tile_put(r,c,attr,tile)         jsp_tile_put((r),(c),(attr),(tile))
#define gfx_tile_register(idx,gfx)          jsp_tile_register((idx),(gfx))

//--- Rectangle operations ---
#define gfx_clear_rect(rect,attr,ch,flags)  jsp_clear_rect((rect),(attr),(ch),(flags))

//--- Text printing ---
#define gfx_print_set_pos(ctx,r,c)          jsp_print_set_pos((ctx),(r),(c))
#define gfx_print_set_clip(ctx,rect)        ((ctx)->clip = (rect))
#define gfx_print_string(ctx,str)           jsp_print_string((ctx),(str))

// Forward declaration for the clipping wrapper (defined in gfx_jsp.c)
// (G4-2) x/y use the gfx_xpos_t / gfx_ypos_t typedefs so the same prototype
// compiles unchanged when CPC/Layer-2 backends widen them to uint16_t.
void gfx_jsp_move_sprite_clipped( gfx_sprite_t *s, gfx_rect_t *clip,
                                   uint8_t *frame, gfx_xpos_t x, gfx_ypos_t y );

#endif // _GFX_JSP_H
