////////////////////////////////////////////////////////////////////////////////
//
// RAGE1 - Retro Adventure Game Engine, release 1
// (c) Copyright 2020 Jorge Gonzalez Villalonga <jorgegv@daikon.es>
//
// This code is published under a GNU GPL license version 3 or later.  See
// LICENSE file in the distribution for details.
//
////////////////////////////////////////////////////////////////////////////////

#ifndef _GFX_SP1_H
#define _GFX_SP1_H

#include <stdint.h>
#include <games/sp1.h>

//--- Types ---
typedef struct sp1_ss    gfx_sprite_t;
typedef struct sp1_Rect  gfx_rect_t;
typedef struct sp1_pss   gfx_print_ctx_t;
typedef uint8_t          gfx_attr_t;

// Pixel coordinate widths (Phase G4 — gfx.md §G4-1).
// On ZX backends 256x192 fits in a byte, so we stay at uint8_t to avoid the
// 16-bit codegen cost.  The CPC backend (Phase G7) will redefine these as
// uint16_t for 320x200 and future ZX Next Layer-2 backends likewise for
// 320x256 / 640x256.  Engine code must use these typedefs at every site that
// holds an integer screen pixel coordinate so the same source compiles on
// both byte- and word-coordinate backends.
typedef uint8_t          gfx_xpos_t;
typedef uint8_t          gfx_ypos_t;

// Tile / glyph identifier (Phase G6 — gfx.md §G6-1).
// On SP1 a tile id is the polysemic uint16_t passed to sp1_PrintAtInv(): values
// < 256 are UDG character codes, values >= 256 are 16-bit tile addresses.  Engine
// code must use this typedef for the tile argument of gfx_tile_put() so the same
// source compiles on the CPC backend (Phase G7), where the id is a backend-internal
// tile-cache index instead.
typedef uint16_t         gfx_tile_id_t;

//--- Constants ---
#define GFX_CLEAR_TILE         SP1_RFLAG_TILE
#define GFX_CLEAR_COLOUR       SP1_RFLAG_COLOUR
#define GFX_PSS_INVALIDATE     SP1_PSSFLAG_INVALIDATE
#define GFX_PRINT_CTX_INIT(area, attr) \
    { &(area), GFX_PSS_INVALIDATE, 0, 0, 0, (attr), 0, 0 }

// Screen geometry in cells (Phase G5 — gfx.md §G5-1).
// SP1 renders the standard ZX Spectrum 32x24 character grid.  The CPC backend
// (Phase G7) will redefine these (mode-1: 40x25), and ZX Next Layer-2 likewise.
// Engine code must use these constants at every site that holds a screen-grid
// dimension so the same source compiles unchanged on backends with a different
// character-cell geometry.
#define GFX_SCREEN_COLS        32
#define GFX_SCREEN_ROWS        24

//--- Attribute layer (ZX-only — inert on CPC, see gfx.md §2.1) ---
// ZX colour indices 0..7 (match arch/spectrum.h INK_*/PAPER_* numeric values)
#define GFX_BLACK              0
#define GFX_BLUE               1
#define GFX_RED                2
#define GFX_MAGENTA            3
#define GFX_GREEN              4
#define GFX_CYAN               5
#define GFX_YELLOW             6
#define GFX_WHITE              7
// Pack ink/paper/bright/flash into the standard ZX attribute byte
#define GFX_ATTR(ink,paper,bright,flash) \
    ( (uint8_t)( ((flash) << 7) | ((bright) << 6) | ((paper) << 3) | (ink) ) )
// Default background attribute (per-game value generated by datagen into DEFAULT_BG_ATTR)
#define GFX_DEFAULT_BG_ATTR    DEFAULT_BG_ATTR

//--- Initialization ---
// gfx_init() is a real function (multi-step), defined in sp1engine.c
#define gfx_invalidate(rect)                   sp1_Invalidate(rect)
#define gfx_update()                           sp1_UpdateNow()
// gfx_set_border() — border colour is consumed on every backend (CPC too).
// On ZX it is a Spectrum colour 0..7; the backend wraps zx_border().
#define gfx_set_border(color)                  zx_border((color))

//--- Sprite lifecycle ---
// gfx_sprite_create() is a real function (multi-step), defined in sprite.c
#define gfx_sprite_destroy(s)                  sp1_DeleteSpr(s)
// gfx_sprite_set_color() is a real function (multi-step), defined in sprite.c
#define gfx_sprite_set_threshold(s,xt,yt) \
    do { (s)->xthresh = (xt); (s)->ythresh = (yt); } while(0)

//--- Sprite movement ---
#define gfx_sprite_move_pixel(s,clip,fr,x,y)   sp1_MoveSprPix((s),(clip),(fr),(x),(y))
#define gfx_sprite_move_cell(s,clip,fr,r,c)    sp1_MoveSprAbs((s),(clip),(fr),(r),(c),0,0)

// Park a sprite off-screen (Phase G5 — gfx.md §G5-4).  The parking row is a
// backend-internal detail: SP1 parks at row 24 (one row below the visible 24-row
// grid), column 0.  Engine code never references the parking row directly; it
// calls gfx_sprite_park() so each backend can choose its own off-screen slot.
#define GFX_PARK_ROW                           24
#define GFX_PARK_COL                           0
#define gfx_sprite_park(s)                     gfx_sprite_move_cell((s),&full_screen,NULL,GFX_PARK_ROW,GFX_PARK_COL)

//--- Sprite query ---
#define gfx_sprite_get_row(s)                  ((s)->row)
#define gfx_sprite_get_col(s)                  ((s)->col)
#define gfx_sprite_get_width(s)                ((s)->width)
#define gfx_sprite_get_height(s)               ((s)->height)

//--- Tile drawing ---
#define gfx_tile_put(r,c,attr,tile)            sp1_PrintAtInv((r),(c),(attr),(tile))
#define gfx_tile_register(idx,gfx)             sp1_TileEntry((idx),(gfx))

//--- Rectangle operations ---
#define gfx_clear_rect(rect,attr,ch,flags)     sp1_ClearRectInv((rect),(attr),(ch),(flags))

//--- Text printing ---
#define gfx_print_set_pos(ctx,r,c)             sp1_SetPrintPos((ctx),(r),(c))
#define gfx_print_set_clip(ctx,rect)           ((ctx)->bounds = (rect))
#define gfx_print_string(ctx,str)              sp1_PrintString((ctx),(str))

#endif // _GFX_SP1_H
