// RAGE1 CPC R3 PoC — PNG-derived sprite rendered on CPC via cpc_asset_convert.pl
//
// Builds on R2: same translated cpctelera primitives (text output stays to
// prove the pipeline), PLUS a PNG-to-CPC-data round-trip:
//   tools/cpc-poc/assets/test.png
//     -> tools/cpc_asset_convert.pl (cpct_img2tileset subprocess)
//     -> tools/cpc-poc/assets/test.c / test.h  (cpctelera pixel arrays)
//     -> compiled and linked into this PoC
//     -> blitted to screen at runtime
//
// The sprite data in test.c/test.h is NOT hand-coded — it is generated by the
// converter from the PNG.  This proves Phase R3 end-to-end.
//
// The PoC deliberately keeps the R2 text output (proves origin) and adds a
// simple row-by-row blit of the PNG-derived sprite above the text.
//
// Build: see tools/cpc-poc/Makefile (adds assets/test.c to sources).

#include <stdint.h>
#include <string.h>

// --- R3: PNG-derived sprite data (generated by cpc_asset_convert.pl) ---
// assets/test.h uses cpctelera's u8 type; assets/types.h provides the shim.
// The build adds -Iassets so <types.h> resolves to our shim (assets/types.h).
#include "assets/test.h"

// --- C-callable ABI of the translated cpctelera primitives (engine/src/cpc) ---
extern void cpct_setVideoMode( uint8_t mode )                 __z88dk_fastcall;
extern void cpct_setPALColour( uint8_t pen, uint8_t hw_ink )  __z88dk_callee;
extern void cpct_setDrawCharM1( uint8_t fg_pen, uint8_t bg_pen ) __z88dk_callee;
extern void cpct_drawStringM1( void *string, void *video_mem )   __z88dk_callee;

// CPC hardware colour values (from cpctelera colours.h)
#define HW_BLACK          0x14
#define HW_BLUE           0x04
#define HW_BRIGHT_YELLOW  0x0A
#define HW_BRIGHT_WHITE   0x0B

#define CPC_VMEM          ((uint8_t *)0xC000)
#define CPC_SCR_BYTES_ROW 0x50u    // 80 bytes per pixel row in mode 1

// ---------------------------------------------------------------------------
// CPC mode-1 screen address for pixel row y, byte offset x
//   addr = vbase + (y % 8) * 0x50 + (y / 8) * 0x800 + x
// ---------------------------------------------------------------------------
static uint8_t *scr_addr(uint16_t y, uint16_t x_byte) {
    return CPC_VMEM + (y & 7u) * CPC_SCR_BYTES_ROW + (y >> 3) * 0x800u + x_byte;
}

// ---------------------------------------------------------------------------
// Blit a cpctelera-format sprite (byte width bw, height h in pixels).
// sprite_data: row-major, bw bytes per row (from the generated .c file).
// y_pix, x_byte: destination pixel row and byte column in screen memory.
// ---------------------------------------------------------------------------
static void blit_sprite(const uint8_t *data,
                        uint8_t bw, uint8_t h,
                        uint16_t y_pix, uint16_t x_byte) {
    for (uint8_t r = 0; r < h; r++) {
        uint8_t *dst = scr_addr(y_pix + r, x_byte);
        memcpy(dst, data + r * (uint16_t)bw, bw);
    }
}

int main(void) {
    __asm
        di                      ;; take the machine from the firmware for the PoC
    __endasm;

    cpct_setVideoMode(1);       // mode 1: 320x200, 4 colours

    // Palette: pen 0 = background (blue), pen 1 = text (bright yellow),
    //          pen 2 = cyan, pen 3 = red
    cpct_setPALColour(0, HW_BLUE);
    cpct_setPALColour(1, HW_BRIGHT_YELLOW);
    cpct_setPALColour(2, HW_BRIGHT_WHITE);  // fw20 = cyan ≈ bright white in HW
    cpct_setPALColour(3, HW_BLACK);

    // Clear the 16K screen to pen 0 (mode-1 pixels all 0)
    for (uint16_t i = 0; i < 0x4000u; i++)
        CPC_VMEM[i] = 0x00u;

    // --- R3: blit the PNG-derived sprite to the top of the screen ---
    // Sprite is 16 pixels wide = 4 bytes, 16 pixels tall.
    // Place it at pixel row 2, byte offset 2 (just past the left border).
    blit_sprite(g_r3sprite, G_R3SPRITE_W, G_R3SPRITE_H, 2, 2);

    // Also blit a second copy to the right for visual confirmation
    blit_sprite(g_r3sprite, G_R3SPRITE_W, G_R3SPRITE_H, 2, 8);
    blit_sprite(g_r3sprite, G_R3SPRITE_W, G_R3SPRITE_H, 2, 14);

    // --- R2: text output (kept to prove the full pipeline) ---
    cpct_setDrawCharM1(1, 0);   // foreground pen 1, background pen 0

    cpct_drawStringM1("RAGE1 CPC  --  R3 PoC",        CPC_VMEM + CPC_SCR_BYTES_ROW *  4 + 8);
    cpct_drawStringM1("PNG->cpct_img2tileset->C->link", CPC_VMEM + CPC_SCR_BYTES_ROW *  6 + 8);
    cpct_drawStringM1("SPRITE ABOVE FROM test.png",    CPC_VMEM + CPC_SCR_BYTES_ROW *  8 + 8);

    __asm
        di                      ;; freeze for a clean emulator screenshot
    __endasm;
    for (;;) { }
    return 0;
}
