section data_compiler
public _tracker_song_game_song
_tracker_song_game_song:
; Just add cream, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Start:
StartDisarkGenerateExternalLabel:

DisarkByteRegionStart0:
	db "AT20"
DisarkPointerRegionStart1:
	dw ArpeggioTable	; The address of the Arpeggio table.
	dw PitchTable	; The address of the Pitch table.
	dw InstrumentTable	; The address of the Instrument table.
	dw EffectBlockTable	; The address of the Effect Block table.
DisarkPointerRegionEnd1:


; The addresses of each Subsong:
DisarkPointerRegionStart2:
	dw Subsong0_Start
DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
ArpeggioTable:
DisarkPointerRegionStart3:
	dw Arpeggio1
	dw Arpeggio2
	dw Arpeggio3
DisarkPointerRegionEnd3:

Arpeggio1:
	db 2	; The speed.

	db 7
	db 4
	db 0
	db -128
DisarkWordForceReference4:
	dw Arpeggio1 + 0 + 1	; Loop.

Arpeggio2:
	db 2	; The speed.

	db 16
	db 12
	db 7
	db -128
DisarkWordForceReference5:
	dw Arpeggio2 + 0 + 1	; Loop.

Arpeggio3:
	db 2	; The speed.

	db 12
	db 7
	db 4
	db -128
DisarkWordForceReference6:
	dw Arpeggio3 + 0 + 1	; Loop.

; Declares all the Pitches.
PitchTable:
DisarkPointerRegionStart7:
	dw Pitch1
DisarkPointerRegionEnd7:

Pitch1:
	db 1	; The speed.

	dw -1
Pitch1_GotoNextForLine0:
DisarkWordForceReference8:
	dw Pitch1_GotoNextForLine0 + 2
	dw -2
Pitch1_GotoNextForLine1:
DisarkWordForceReference9:
	dw Pitch1_GotoNextForLine1 + 2
	dw -3
Pitch1_GotoNextForLine2:
DisarkWordForceReference10:
	dw Pitch1_GotoNextForLine2 + 2
	dw -2
Pitch1_GotoNextForLine3:
DisarkWordForceReference11:
	dw Pitch1_GotoNextForLine3 + 2
	dw -1
Pitch1_GotoNextForLine4:
DisarkWordForceReference12:
	dw Pitch1_GotoNextForLine4 + 2
	dw 1
Pitch1_GotoNextForLine5:
DisarkWordForceReference13:
	dw Pitch1_GotoNextForLine5 + 2
	dw 2
Pitch1_GotoNextForLine6:
DisarkWordForceReference14:
	dw Pitch1_GotoNextForLine6 + 2
	dw 3
Pitch1_GotoNextForLine7:
DisarkWordForceReference15:
	dw Pitch1_GotoNextForLine7 + 2
	dw 2
DisarkWordForceReference16:
	dw Pitch1 + 4 * 0 + 1

; Declares all the Instruments.
InstrumentTable:
DisarkPointerRegionStart17:
	dw EmptyInstrument
	dw Instrument1
	dw Instrument2
	dw Instrument3
	dw Instrument4
	dw Instrument5
	dw Instrument6
	dw Instrument7
	dw Instrument8
	dw Instrument9
	dw Instrument10
	dw Instrument11
DisarkPointerRegionEnd17:

EmptyInstrument:
	db 0	; The speed (>0, 0 for 256).
EmptyInstrument_Loop:	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Instrument1:
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 159	; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
	dw 956	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1012	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1276	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1517	; Forced period.

	db 105	; Soft only. Volume: 13.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 2408	; Forced period.

	db 6	; Loop to silence.

Instrument2:
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 145	; Additional data. Noise: 17. Pitch? false. Arp? false. Period? true.
	dw 426	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 536	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 638	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 716	; Forced period.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 13	; Noise: 13.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 13	; Noise: 13.

	db 6	; Loop to silence.

Instrument3:
	db 1	; The speed (>0, 0 for 256).
	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 130	; Simple case. Ratio: 5

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 130	; Simple case. Ratio: 5

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

Instrument3_Loop:	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
DisarkWordForceReference18:
	dw Instrument3_Loop	; Loop here.

Instrument4:
	db 1	; The speed (>0, 0 for 256).
	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

Instrument4_Loop:	db 201	; Soft only. Volume: 9. Volume only.

	db 7	; Loop.
DisarkWordForceReference19:
	dw Instrument4_Loop	; Loop here.

Instrument5:
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 159	; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
	dw 956	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1012	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1276	; Forced period.

	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 1517	; Forced period.

Instrument5_Loop:	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
DisarkWordForceReference20:
	dw Instrument5_Loop	; Loop here.

Instrument6:
	db 1	; The speed (>0, 0 for 256).
	db 113	; Soft only. Volume: 14.
	db 145	; Additional data. Noise: 17. Pitch? false. Arp? false. Period? true.
	dw 426	; Forced period.

	db 113	; Soft only. Volume: 14.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 536	; Forced period.

	db 113	; Soft only. Volume: 14.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 638	; Forced period.

	db 113	; Soft only. Volume: 14.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 716	; Forced period.

	db 224	; No Soft no Hard. Volume: 12. Noise? true.
	db 13	; Noise: 13.

Instrument6_Loop:	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
DisarkWordForceReference21:
	dw Instrument6_Loop	; Loop here.

Instrument7:
	db 1	; The speed (>0, 0 for 256).
	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

Instrument7_Loop:	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
DisarkWordForceReference22:
	dw Instrument7_Loop	; Loop here.

Instrument8:
	db 1	; The speed (>0, 0 for 256).
Instrument8_Loop:	db 193	; Soft only. Volume: 8. Volume only.

	db 7	; Loop.
DisarkWordForceReference23:
	dw Instrument8_Loop	; Loop here.

Instrument9:
	db 1	; The speed (>0, 0 for 256).
	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 185	; Soft only. Volume: 7. Volume only.

Instrument9_Loop:	db 177	; Soft only. Volume: 6. Volume only.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 7	; Loop.
DisarkWordForceReference24:
	dw Instrument9_Loop	; Loop here.

Instrument10:
	db 1	; The speed (>0, 0 for 256).
	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 161	; Soft only. Volume: 4. Volume only.

Instrument10_Loop:	db 153	; Soft only. Volume: 3. Volume only.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

	db 7	; Loop.
DisarkWordForceReference25:
	dw Instrument10_Loop	; Loop here.

Instrument11:
	db 1	; The speed (>0, 0 for 256).
	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

Instrument11_Loop:	db 145	; Soft only. Volume: 2. Volume only.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 145	; Soft only. Volume: 2. Volume only.

	db 7	; Loop.
DisarkWordForceReference26:
	dw Instrument11_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
EffectBlockTable:
DisarkPointerRegionStart27:
	dw EffectBlock_P4P0	; Index 0
	dw EffectBlock_P14P64P0	; Index 1
	dw EffectBlock_P4P1	; Index 2
	dw EffectBlock_P5P0P14P64P0	; Index 3
	dw EffectBlock_P5P0P6P2	; Index 4
	dw EffectBlock_P5P0P10P0	; Index 5
	dw EffectBlock_P15P112P0P12	; Index 6
	dw EffectBlock_P5P0P6P1	; Index 7
	dw EffectBlock_P15P64P0P6P1	; Index 8
	dw EffectBlock_P5P0P6P0	; Index 9
	dw EffectBlock_P6P1	; Index 10
	dw EffectBlock_P5P0P14P112P0	; Index 11
	dw EffectBlock_P5P0P14P160P0	; Index 12
	dw EffectBlock_P5P0P15P64P0P6P2	; Index 13
	dw EffectBlock_P5P0P15P64P0P6P0	; Index 14
	dw EffectBlock_P14P160P0	; Index 15
	dw EffectBlock_P10P0	; Index 16
	dw EffectBlock_P15P64P0P6P0	; Index 17
	dw EffectBlock_P20P0P5	; Index 18
	dw EffectBlock_P5P0P13P18P0P1	; Index 19
	dw EffectBlock_P5P0P15P112P0P12	; Index 20
	dw EffectBlock_P5P0P18P0P2	; Index 21
	dw EffectBlock_P4P2	; Index 22
	dw EffectBlock_P15P64P0P20P0P16	; Index 23
	dw EffectBlock_P24P60P0P2	; Index 24
	dw EffectBlock_P24P64P0P1	; Index 25
	dw EffectBlock_P15P64P0P6P2	; Index 26
	dw EffectBlock_P6P2	; Index 27
	dw EffectBlock_P24P59P128P1	; Index 28
	dw EffectBlock_P13P18P128P1	; Index 29
	dw EffectBlock_P24P57P0P3	; Index 30
	dw EffectBlock_P5P14P15P128P255P13P6P1	; Index 31
	dw EffectBlock_P6P0	; Index 32
	dw EffectBlock_P15P8P0P20P0P6	; Index 33
	dw EffectBlock_P5P0P8	; Index 34
	dw EffectBlock_P5P0P18P128P1	; Index 35
	dw EffectBlock_P5P0P18P0P12	; Index 36
	dw EffectBlock_P4P3	; Index 37
	dw EffectBlock_P24P23P0P12	; Index 38
	dw EffectBlock_P24P48P128P1	; Index 39
	dw EffectBlock_P5P0P13P8	; Index 40
	dw EffectBlock_P14P8P0	; Index 41
	dw EffectBlock_P20P0P1	; Index 42
	dw EffectBlock_P14P32P0	; Index 43
	dw EffectBlock_P12	; Index 44
	dw EffectBlock_P14P112P0	; Index 45
	dw EffectBlock_P4P5	; Index 46
	dw EffectBlock_P4P4	; Index 47
DisarkPointerRegionEnd27:

EffectBlock_P12:
	db 12
EffectBlock_P4P0:
	db 4, 0
EffectBlock_P4P1:
	db 4, 1
EffectBlock_P4P2:
	db 4, 2
EffectBlock_P4P3:
	db 4, 3
EffectBlock_P4P4:
	db 4, 4
EffectBlock_P4P5:
	db 4, 5
EffectBlock_P6P0:
	db 6, 0
EffectBlock_P6P1:
	db 6, 1
EffectBlock_P6P2:
	db 6, 2
EffectBlock_P10P0:
	db 10, 0
EffectBlock_P5P0P8:
	db 5, 0, 8
EffectBlock_P14P8P0:
	db 14, 8, 0
EffectBlock_P20P0P1:
	db 20, 0, 1
EffectBlock_P20P0P5:
	db 20, 0, 5
EffectBlock_P14P32P0:
	db 14, 32, 0
EffectBlock_P14P64P0:
	db 14, 64, 0
EffectBlock_P5P0P6P0:
	db 5, 0, 6, 0
EffectBlock_P5P0P6P1:
	db 5, 0, 6, 1
EffectBlock_P5P0P6P2:
	db 5, 0, 6, 2
EffectBlock_P5P14P15P128P255P13P6P1:
	db 5, 14, 15, 128, 255, 13, 6, 1
EffectBlock_P15P112P0P12:
	db 15, 112, 0, 12
EffectBlock_P15P64P0P6P0:
	db 15, 64, 0, 6, 0
EffectBlock_P15P64P0P6P1:
	db 15, 64, 0, 6, 1
EffectBlock_P15P64P0P6P2:
	db 15, 64, 0, 6, 2
EffectBlock_P14P112P0:
	db 14, 112, 0
EffectBlock_P14P160P0:
	db 14, 160, 0
EffectBlock_P5P0P10P0:
	db 5, 0, 10, 0
EffectBlock_P5P0P13P8:
	db 5, 0, 13, 8
EffectBlock_P24P23P0P12:
	db 24, 23, 0, 12
EffectBlock_P5P0P15P112P0P12:
	db 5, 0, 15, 112, 0, 12
EffectBlock_P5P0P15P64P0P6P0:
	db 5, 0, 15, 64, 0, 6, 0
EffectBlock_P5P0P15P64P0P6P2:
	db 5, 0, 15, 64, 0, 6, 2
EffectBlock_P5P0P14P112P0:
	db 5, 0, 14, 112, 0
EffectBlock_P5P0P14P160P0:
	db 5, 0, 14, 160, 0
EffectBlock_P5P0P18P128P1:
	db 5, 0, 18, 128, 1
EffectBlock_P15P64P0P20P0P16:
	db 15, 64, 0, 20, 0, 16
EffectBlock_P5P0P18P0P2:
	db 5, 0, 18, 0, 2
EffectBlock_P5P0P14P64P0:
	db 5, 0, 14, 64, 0
EffectBlock_P5P0P18P0P12:
	db 5, 0, 18, 0, 12
EffectBlock_P5P0P13P18P0P1:
	db 5, 0, 13, 18, 0, 1
EffectBlock_P24P57P0P3:
	db 24, 57, 0, 3
EffectBlock_P24P60P0P2:
	db 24, 60, 0, 2
EffectBlock_P24P64P0P1:
	db 24, 64, 0, 1
EffectBlock_P13P18P128P1:
	db 13, 18, 128, 1
EffectBlock_P24P48P128P1:
	db 24, 48, 128, 1
EffectBlock_P24P59P128P1:
	db 24, 59, 128, 1
EffectBlock_P15P8P0P20P0P6:
	db 15, 8, 0, 20, 0, 6

DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0:
Subsong0_Start:
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 4	; Loop start index (>=0).
	db 27	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 9	; Base note index (>=0).

Subsong0_Linker:
Subsong0_DisarkPointerRegionStart1:
; Position 0
	dw Subsong0_Track17
	dw Subsong0_Track22
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock0

; Position 1
	dw Subsong0_Track18
	dw Subsong0_Track21
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock0

; Position 2
	dw Subsong0_Track2
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock0

; Position 3
	dw Subsong0_Track2
	dw Subsong0_Track0
	dw Subsong0_Track29
	dw Subsong0_LinkerBlock0

; Position 4
Subsong0_Linker_Loop:
	dw Subsong0_Track2
	dw Subsong0_Track3
	dw Subsong0_Track1
	dw Subsong0_LinkerBlock0

; Position 5
	dw Subsong0_Track24
	dw Subsong0_Track25
	dw Subsong0_Track26
	dw Subsong0_LinkerBlock0

; Position 6
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock0

; Position 7
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track23
	dw Subsong0_LinkerBlock0

; Position 8
	dw Subsong0_Track9
	dw Subsong0_Track7
	dw Subsong0_Track30
	dw Subsong0_LinkerBlock1

; Position 9
	dw Subsong0_Track10
	dw Subsong0_Track8
	dw Subsong0_Track30
	dw Subsong0_LinkerBlock1

; Position 10
	dw Subsong0_Track11
	dw Subsong0_Track7
	dw Subsong0_Track30
	dw Subsong0_LinkerBlock1

; Position 11
	dw Subsong0_Track12
	dw Subsong0_Track8
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock1

; Position 12
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock0

; Position 13
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock0

; Position 14
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock0

; Position 15
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track23
	dw Subsong0_LinkerBlock0

; Position 16
	dw Subsong0_Track9
	dw Subsong0_Track7
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 17
	dw Subsong0_Track10
	dw Subsong0_Track8
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 18
	dw Subsong0_Track11
	dw Subsong0_Track7
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 19
	dw Subsong0_Track12
	dw Subsong0_Track8
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 20
	dw Subsong0_Track13
	dw Subsong0_Track28
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 21
	dw Subsong0_Track14
	dw Subsong0_Track28
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 22
	dw Subsong0_Track15
	dw Subsong0_Track28
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 23
	dw Subsong0_Track16
	dw Subsong0_Track28
	dw Subsong0_Track27
	dw Subsong0_LinkerBlock1

; Position 24
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock0

; Position 25
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock0

; Position 26
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track5
	dw Subsong0_LinkerBlock0

; Position 27
	dw Subsong0_Track4
	dw Subsong0_Track3
	dw Subsong0_Track23
	dw Subsong0_LinkerBlock0

Subsong0_DisarkPointerRegionEnd1:
	dw 0	; Loop.
Subsong0_DisarkWordForceReference2:
	dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0:
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference3:
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference4:
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock1:
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference5:
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference6:
	dw Subsong0_EventTrack0	; EventTrack address.

Subsong0_Track0:
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track1:
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track2:
	db 204
	db 3	; New Instrument (3).
	db 34	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 140
	db 3	; New Instrument (3).
	db 10
	db 12
	db 60	; Waits for 1 line.

	db 15
	db 128
	db 0	; New Instrument (0).
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 133
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 145
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 17
	db 15
	db 17
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 148
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 136
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 148
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 20
	db 15
	db 20
	db 60	; Waits for 1 line.

	db 22
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 143
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 138
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 143
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 22
	db 10
	db 14
	db 60	; Waits for 1 line.

	db 17
	db 128
	db 0	; New Instrument (0).
	db 142
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 10
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track3:
	db 231
	db 4	; New Instrument (4).
	db 9	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 14	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 17	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 13	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 9	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 108
	db 27	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 46
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 108
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 115
	db 32	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 115
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 110
	db 9	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 26	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track4:
	db 204
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 6	; New Instrument (6).
	db 128
	db 0	; New Instrument (0).
	db 140
	db 3	; New Instrument (3).
	db 10
	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 143
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 140
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 145
	db 5	; New Instrument (5).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 133
	db 5	; New Instrument (5).
	db 128
	db 0	; New Instrument (0).
	db 145
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 145
	db 3	; New Instrument (3).
	db 15
	db 145
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 212
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 20
	db 128
	db 0	; New Instrument (0).
	db 136
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 148
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 148
	db 3	; New Instrument (3).
	db 15
	db 148
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 207
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 138
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 143
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 150
	db 3	; New Instrument (3).
	db 10
	db 142
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 17
	db 128
	db 0	; New Instrument (0).
	db 142
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 138
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track5:
	db 246
	db 7	; New Instrument (7).
	db 19	; Index to an effect block.
	db 124	; No note, but effects.
	db 25	; Index to an effect block.
	db 112
	db 12	; Index to an effect block.
	db 247
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 181
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 179
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 243
	db 7	; New Instrument (7).
	db 15	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 12	; Index to an effect block.
	db 242
	db 7	; New Instrument (7).
	db 21	; Index to an effect block.
	db 124	; No note, but effects.
	db 24	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 235
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 107
	db 1	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 112
	db 3	; Index to an effect block.
	db 235
	db 8	; New Instrument (8).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 236
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 1	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 20	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 11	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 11	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 231
	db 7	; New Instrument (7).
	db 1	; Index to an effect block.
	db 235
	db 8	; New Instrument (8).
	db 11	; Index to an effect block.
	db 230
	db 7	; New Instrument (7).
	db 35	; Index to an effect block.
	db 124	; No note, but effects.
	db 39	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 43	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track6:
	db 246
	db 7	; New Instrument (7).
	db 19	; Index to an effect block.
	db 124	; No note, but effects.
	db 25	; Index to an effect block.
	db 112
	db 12	; Index to an effect block.
	db 247
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 181
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 179
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 243
	db 7	; New Instrument (7).
	db 15	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 12	; Index to an effect block.
	db 242
	db 7	; New Instrument (7).
	db 21	; Index to an effect block.
	db 124	; No note, but effects.
	db 24	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 235
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 107
	db 1	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 112
	db 3	; Index to an effect block.
	db 235
	db 8	; New Instrument (8).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 236
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 1	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 20	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 11	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 30	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 174
	db 8	; New Instrument (8).
	db 238
	db 7	; New Instrument (7).
	db 16	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 176
	db 8	; New Instrument (8).
	db 243
	db 7	; New Instrument (7).
	db 44	; Index to an effect block.
	db 238
	db 8	; New Instrument (8).
	db 16	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 241
	db 7	; New Instrument (7).
	db 29	; Index to an effect block.
	db 124	; No note, but effects.
	db 28	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 112
	db 6	; Index to an effect block.
	db 242
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 44	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 45	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 11	; Index to an effect block.
	db 238
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track7:
	db 195
	db 1	; New Instrument (1).
	db 40	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 3
	db 61, 127	; Waits for 128 lines.


Subsong0_Track8:
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 61, 127	; Waits for 128 lines.


Subsong0_Track9:
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 152
	db 3	; New Instrument (3).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 138
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 139
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track10:
	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 3	; New Instrument (3).
	db 22
	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 147
	db 3	; New Instrument (3).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track11:
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 152
	db 3	; New Instrument (3).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 3	; New Instrument (3).
	db 24
	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 12
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 148
	db 3	; New Instrument (3).
	db 24
	db 27
	db 128
	db 0	; New Instrument (0).
	db 150
	db 3	; New Instrument (3).
	db 26
	db 29
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track12:
	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 10
	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 150
	db 3	; New Instrument (3).
	db 10
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 23
	db 61, 127	; Waits for 128 lines.


Subsong0_Track13:
	db 204
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 216
	db 6	; New Instrument (6).
	db 0	; Index to an effect block.
	db 147
	db 5	; New Instrument (5).
	db 128
	db 0	; New Instrument (0).
	db 150
	db 5	; New Instrument (5).
	db 128
	db 0	; New Instrument (0).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 152
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 202
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 131
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 139
	db 6	; New Instrument (6).
	db 11
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track14:
	db 216
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 5	; New Instrument (5).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 131
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 152
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 214
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 150
	db 6	; New Instrument (6).
	db 131
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 147
	db 6	; New Instrument (6).
	db 147
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track15:
	db 204
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 216
	db 6	; New Instrument (6).
	db 0	; Index to an effect block.
	db 147
	db 5	; New Instrument (5).
	db 128
	db 0	; New Instrument (0).
	db 150
	db 5	; New Instrument (5).
	db 152
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 152
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 212
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 152
	db 3	; New Instrument (3).
	db 155
	db 5	; New Instrument (5).
	db 128
	db 0	; New Instrument (0).
	db 150
	db 6	; New Instrument (6).
	db 26
	db 157
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track16:
	db 216
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 5	; New Instrument (5).
	db 19
	db 128
	db 0	; New Instrument (0).
	db 150
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 10
	db 128
	db 0	; New Instrument (0).
	db 152
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 214
	db 6	; New Instrument (6).
	db 0	; Index to an effect block.
	db 138
	db 5	; New Instrument (5).
	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 214
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 139
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 151
	db 3	; New Instrument (3).
	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track17:
	db 128
	db 0	; New Instrument (0).
	db 61, 14	; Waits for 15 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 12	; Waits for 13 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 12	; Waits for 13 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 10	; Waits for 11 lines.

	db 138
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track18:
	db 204
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 143
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 23	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 205
	db 3	; New Instrument (3).
	db 36	; Index to an effect block.
	db 124	; No note, but effects.
	db 38	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 23	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track19:
	db 124	; No note, but effects.
	db 41	; Index to an effect block.
	db 61, 22	; Waits for 23 lines.

	db 124	; No note, but effects.
	db 42	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track20:
	db 128
	db 0	; New Instrument (0).
	db 61, 52	; Waits for 53 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 61, 127	; Waits for 128 lines.


Subsong0_Track21:
	db 231
	db 4	; New Instrument (4).
	db 9	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 14	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 17	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 13	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 9	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 108
	db 27	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 46
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 108
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 115
	db 32	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 115
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 110
	db 9	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 27	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track22:
	db 231
	db 4	; New Instrument (4).
	db 31	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 103
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 14	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 17	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 13	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 9	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 108
	db 27	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 46
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 108
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 115
	db 32	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 115
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 110
	db 9	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 26	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track23:
	db 246
	db 7	; New Instrument (7).
	db 19	; Index to an effect block.
	db 124	; No note, but effects.
	db 25	; Index to an effect block.
	db 112
	db 12	; Index to an effect block.
	db 247
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 181
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 179
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 112
	db 15	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 243
	db 7	; New Instrument (7).
	db 15	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 12	; Index to an effect block.
	db 242
	db 7	; New Instrument (7).
	db 21	; Index to an effect block.
	db 124	; No note, but effects.
	db 24	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 243
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 117
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 235
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 245
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 107
	db 1	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 112
	db 3	; Index to an effect block.
	db 235
	db 8	; New Instrument (8).
	db 3	; Index to an effect block.
	db 110
	db 3	; Index to an effect block.
	db 236
	db 7	; New Instrument (7).
	db 5	; Index to an effect block.
	db 240
	db 8	; New Instrument (8).
	db 1	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 20	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 235
	db 7	; New Instrument (7).
	db 11	; Index to an effect block.
	db 236
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 172
	db 7	; New Instrument (7).
	db 235
	db 8	; New Instrument (8).
	db 6	; Index to an effect block.
	db 238
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 30	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 174
	db 8	; New Instrument (8).
	db 238
	db 7	; New Instrument (7).
	db 16	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 176
	db 8	; New Instrument (8).
	db 243
	db 7	; New Instrument (7).
	db 44	; Index to an effect block.
	db 238
	db 8	; New Instrument (8).
	db 16	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 241
	db 7	; New Instrument (7).
	db 29	; Index to an effect block.
	db 124	; No note, but effects.
	db 28	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 112
	db 6	; Index to an effect block.
	db 242
	db 8	; New Instrument (8).
	db 5	; Index to an effect block.
	db 174
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 33	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track24:
	db 204
	db 3	; New Instrument (3).
	db 34	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 152
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 140
	db 3	; New Instrument (3).
	db 10
	db 12
	db 60	; Waits for 1 line.

	db 15
	db 128
	db 0	; New Instrument (0).
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 133
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 145
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 17
	db 15
	db 17
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 148
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 136
	db 3	; New Instrument (3).
	db 128
	db 0	; New Instrument (0).
	db 148
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 20
	db 15
	db 20
	db 60	; Waits for 1 line.

	db 22
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 143
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 15
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 5	; Waits for 6 lines.

	db 152
	db 3	; New Instrument (3).
	db 12
	db 60	; Waits for 1 line.

	db 10
	db 61, 127	; Waits for 128 lines.


Subsong0_Track25:
	db 231
	db 4	; New Instrument (4).
	db 9	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 14	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 17	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 13	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 110
	db 9	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 108
	db 27	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 0	; Index to an effect block.
	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 108
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 46
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 108
	db 7	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 115
	db 32	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 115
	db 46	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 115
	db 47	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 115
	db 37	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 115
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 115
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track26:
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 61, 8	; Waits for 9 lines.

	db 195
	db 2	; New Instrument (2).
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track27:
	db 171
	db 11	; New Instrument (11).
	db 48
	db 243
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 50
	db 179
	db 10	; New Instrument (10).
	db 174
	db 9	; New Instrument (9).
	db 178
	db 10	; New Instrument (10).
	db 179
	db 11	; New Instrument (11).
	db 179
	db 9	; New Instrument (9).
	db 50
	db 179
	db 11	; New Instrument (11).
	db 174
	db 9	; New Instrument (9).
	db 178
	db 10	; New Instrument (10).
	db 179
	db 11	; New Instrument (11).
	db 174
	db 10	; New Instrument (10).
	db 178
	db 11	; New Instrument (11).
	db 51
	db 46
	db 171
	db 9	; New Instrument (9).
	db 46
	db 174
	db 11	; New Instrument (11).
	db 176
	db 9	; New Instrument (9).
	db 174
	db 10	; New Instrument (10).
	db 43
	db 171
	db 9	; New Instrument (9).
	db 46
	db 171
	db 10	; New Instrument (10).
	db 176
	db 9	; New Instrument (9).
	db 174
	db 10	; New Instrument (10).
	db 171
	db 11	; New Instrument (11).
	db 176
	db 10	; New Instrument (10).
	db 174
	db 11	; New Instrument (11).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track28:
	db 174
	db 11	; New Instrument (11).
	db 51
	db 247
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 53
	db 183
	db 10	; New Instrument (10).
	db 178
	db 9	; New Instrument (9).
	db 181
	db 10	; New Instrument (10).
	db 183
	db 11	; New Instrument (11).
	db 183
	db 9	; New Instrument (9).
	db 53
	db 183
	db 11	; New Instrument (11).
	db 178
	db 9	; New Instrument (9).
	db 181
	db 10	; New Instrument (10).
	db 183
	db 11	; New Instrument (11).
	db 178
	db 10	; New Instrument (10).
	db 181
	db 11	; New Instrument (11).
	db 55
	db 50
	db 174
	db 9	; New Instrument (9).
	db 50
	db 178
	db 11	; New Instrument (11).
	db 179
	db 9	; New Instrument (9).
	db 178
	db 10	; New Instrument (10).
	db 46
	db 174
	db 9	; New Instrument (9).
	db 50
	db 174
	db 11	; New Instrument (11).
	db 179
	db 9	; New Instrument (9).
	db 178
	db 10	; New Instrument (10).
	db 174
	db 11	; New Instrument (11).
	db 179
	db 10	; New Instrument (10).
	db 178
	db 11	; New Instrument (11).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track29:
	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 195
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 22	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 195
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 37	; Index to an effect block.
	db 67
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Subsong0_Track30:
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0:
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 14	; Value: 7.
	db 10	; Value: 5.
	db 127	; Wait for 64 lines.

; The event tracks
Subsong0_EventTrack0:
	db 255	; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0:
