; nosound, AKG format, v1.0.

; Generated by Arkos Tracker 2.

nosound_Start:
nosound_StartDisarkGenerateExternalLabel:

nosound_DisarkByteRegionStart0:
	db "AT20"
nosound_DisarkPointerRegionStart1:
	dw nosound_ArpeggioTable	; The address of the Arpeggio table.
	dw nosound_PitchTable	; The address of the Pitch table.
	dw nosound_InstrumentTable	; The address of the Instrument table.
	dw nosound_EffectBlockTable	; The address of the Effect Block table.
nosound_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
nosound_DisarkPointerRegionStart2:
	dw nosound_Subsong0_Start
nosound_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
nosound_ArpeggioTable:
nosound_DisarkPointerRegionStart3:
nosound_DisarkPointerRegionEnd3:

; Declares all the Pitches.
nosound_PitchTable:
nosound_DisarkPointerRegionStart4:
nosound_DisarkPointerRegionEnd4:

; Declares all the Instruments.
nosound_InstrumentTable:
nosound_DisarkPointerRegionStart5:
	dw nosound_EmptyInstrument
nosound_DisarkPointerRegionEnd5:

nosound_EmptyInstrument:
	db 0	; The speed (>0, 0 for 256).
nosound_EmptyInstrument_Loop:	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
nosound_EffectBlockTable:

nosound_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
nosound_Subsong0_DisarkByteRegionStart0:
nosound_Subsong0_Start:
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

nosound_Subsong0_Linker:
nosound_Subsong0_DisarkPointerRegionStart1:
; Position 0
nosound_Subsong0_Linker_Loop:
	dw nosound_Subsong0_Track0
	dw nosound_Subsong0_Track0
	dw nosound_Subsong0_Track0
	dw nosound_Subsong0_LinkerBlock0

nosound_Subsong0_DisarkPointerRegionEnd1:
	dw 0	; Loop.
nosound_Subsong0_DisarkWordForceReference2:
	dw nosound_Subsong0_Linker_Loop

nosound_Subsong0_LinkerBlock0:
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
nosound_Subsong0_DisarkWordForceReference3:
	dw nosound_Subsong0_SpeedTrack0	; SpeedTrack address.
nosound_Subsong0_DisarkWordForceReference4:
	dw nosound_Subsong0_EventTrack0	; EventTrack address.

nosound_Subsong0_Track0:
	db 61, 127	; Waits for 128 lines.


; The speed tracks
nosound_Subsong0_SpeedTrack0:
	db 255	; Wait for 128 lines.

; The event tracks
nosound_Subsong0_EventTrack0:
	db 255	; Wait for 128 lines.

nosound_Subsong0_DisarkByteRegionEnd0:
