// RAGE1 CPC hello-world test game (T2-10)
//
// This is a minimal standalone C programme that proves the
// zcc +cpc toolchain pipeline end-to-end:
//
//   datagen.pl -p cpc464  ->  features.h (PLATFORM_CPC464 / PLATFORM_CPC_FLAT)
//   zcc +cpc -compiler=sdcc  ->  main.bin
//   appmake +cpc -subtype=dsk  ->  game.dsk
//
// The RAGE1 engine is NOT included at this phase.  Full CPC engine
// integration awaits the CPC gfx/audio/input HAL backends (Phase
// G7 / IN5 / AU4).  See doc/multiplatform-plan/toolchain.md §T2-10.
//
// Rendering: uses the z88dk +cpc CRT's built-in stdio (printk /
// putchar_cons) which the +cpc CRT wires through the firmware
// character output routine while the firmware is still active.
// This avoids the lower-ROM-paging workaround used in the R2 PoC
// (org 0x4000) and works correctly at the designed org 0x1200.
//
// PoC: org 0x1200 (CRT_ORG_CODE from zpragma-cpc-flat.inc).

#include <stdint.h>

// features.h is generated by datagen.pl -p cpc464 and should contain:
//   BUILD_FEATURE_PLATFORM_CPC464
//   BUILD_FEATURE_PLATFORM_CPC_FLAT
// Include it to verify the datagen pipeline is working.
// It is placed in build/generated/ which is on the include path.
#ifdef __SDCC
// features.h may not exist if this file is compiled directly;
// guard so that a missing file becomes a clear linker/build error
// rather than a silent preprocessor no-op.
#include "features.h"
#endif

// Sanity check: fail to compile if datagen.pl did not emit the CPC macros.
#ifndef BUILD_FEATURE_PLATFORM_CPC464
#error "BUILD_FEATURE_PLATFORM_CPC464 not defined — did datagen.pl run with -p cpc464?"
#endif
#ifndef BUILD_FEATURE_PLATFORM_CPC_FLAT
#error "BUILD_FEATURE_PLATFORM_CPC_FLAT not defined — did datagen.pl run with -p cpc464?"
#endif

// z88dk +cpc CRT stdio (firmware-backed character output).
// printk() is the z88dk equivalent of printf() for embedded targets.
extern int printk(const char *fmt, ...);

int main(void) {
    // Use z88dk +cpc CRT stdio — firmware is still active at this phase,
    // so putchar/printk routes through the Locomotive BASIC character
    // output firmware routine.  No mode-switch or palette-init needed;
    // the CPC boots in mode 1 (4-colour, 40-column text) by default.

    printk("RAGE1 CPC Hello-World\r\n");
    printk("Phase T2 — cpc-flat bring-up\r\n");
    printk("\r\n");
    printk("PLATFORM: cpc464 (cpc-flat)\r\n");
    printk("ORG:      0x1200 (CRT_ORG_CODE)\r\n");
    printk("STACK:    0xBF00 (below screen RAM)\r\n");
    printk("\r\n");
    printk("Toolchain OK — game.dsk produced.\r\n");

    // Freeze so the emulator screenshot can be taken.
    for (;;) { }

    return 0;
}
