#!/usr/bin/env perl

################################################################################
##
## RAGE1 - Retro Adventure Game Engine, release 1
## (c) Copyright 2020 Jorge Gonzalez Villalonga <jorgegv@daikon.es>
##
## This code is published under a GNU GPL license version 3 or later.  See
## LICENSE file in the distribution for details.
##
################################################################################

##
## bankscaffoldtool.pl — z88dk-native banking scaffold generator (cpc-banked)
##
## Emits a small z80asm source that, for each POPULATED bank binary
## (build/generated/bank_<n>.bin from banktool.pl), declares the matching
## z88dk `SECTION BANK_<n>` and `BINARY`-incbins the bank payload into it.
##
## This scaffold is linked into the resident engine image (GAME): the linker
## splits each BANK_<n> section into its own output binary (the section is
## org'ed at 0xc<n>0000+0x4000 by the custom mmap-cpc-banked.inc), and appmake
## `+cpc --disk` (driven by `zcc -create-app -subtype=dsk`) then emits one
## AMSDOS-headered disc file per populated bank (`<MAIN>.b<n>`) and patches the
## main image's `__crt_loader_filename`.  At boot, z88dk's stock `loadbanks`
## (run in pristine firmware state at crt0, before the exx-seize) streams each
## `<MAIN>.B<n>` into its physical RAM bank at 0x4000 via the firmware CAS
## routines.  This replaces the old hand-rolled LOADER.BIN + streaming
## asmloader, which could not coexist with a large CAS_IN_DIRECT (see
## doc/multiplatform-plan/management/cpc-banked-bringup.md, step 10 redesign).
##
## bank_<n>.bin offset 0 maps to address 0x4000 in bank <n> (banks 4-7 page
## into the 0x4000 swap window: CRT_ORG_BANK_4..7 = 0x4000), matching RAGE1's
## DATASET_LOAD_BASE (0x4000) and the dataset_info offsets — so the payload is
## incbin'd verbatim with no re-layout.
##

use strict;
use warnings;
use utf8;
use Getopt::Std;
use Cwd qw( abs_path );
use File::Basename;

# config
my $bank_binaries_glob   = 'bank_*.bin';
my $scaffold_output_name = 'bank_scaffold.asm';

binmode STDOUT, ':encoding(UTF-8)';

# parse command options
our ( $opt_i, $opt_o, $opt_p );
getopts( "i:o:p:" );
( defined( $opt_i ) and defined( $opt_o ) ) or
    die "usage: $0 -i <bank_bin_dir> -o <output_dir> [-p <platform>]\n";

my ( $input_dir, $output_dir ) = ( $opt_i, $opt_o );

# platform defaults to cpc-banked (the only platform that uses this scaffold
# today; ZX 128 banking is packaged into the .tap loader, not z88dk sections).
my $platform = $opt_p // 'cpc-banked';
if ( $platform ne 'cpc-banked' ) {
    print "bankscaffoldtool.pl: platform=$platform does not use a bank scaffold — nothing to do\n";
    exit 0;
}

# gather populated bank binaries: build/generated/bank_<n>.bin
my @banks;
opendir my $bindir, $input_dir or
    die "** Error: could not open directory $input_dir for reading\n";
foreach my $bin ( sort readdir $bindir ) {
    next unless $bin =~ m/^bank_(\d+)\.bin$/;
    my $n    = $1;
    my $path = "$input_dir/$bin";
    my $size = ( stat( $path ) )[7] // 0;
    # a zero-byte bank file is not populated (banktool emits none, but be safe)
    next unless $size > 0;
    push @banks, {
        'num'  => $n,
        'size' => $size,
        # absolute path: zcc relocates link sources into its own temp build
        # dir, so a cwd-relative BINARY path is unreliable (same reason the
        # Makefile passes an absolute -crt0=).
        'path' => abs_path( $path ),
    };
}
closedir $bindir;

# sort by bank number for stable, readable output
@banks = sort { $a->{'num'} <=> $b->{'num'} } @banks;

# emit the scaffold
my $out_path = "$output_dir/$scaffold_output_name";
open my $out, '>', $out_path or
    die "** Error: could not open $out_path for writing: $!\n";
binmode $out, ':encoding(UTF-8)';

print $out <<"HEADER";
;; ----------------------------------------------------------------------------
;; RAGE1 cpc-banked — z88dk bank scaffold (GENERATED by tools/bankscaffoldtool.pl)
;;
;; One `SECTION BANK_<n>` + `BINARY` per populated bank.  The BANK_<n> sections
;; (org, sub-section ordering, __BANK_<n>_END markers) are declared by the
;; custom linker map mmap-cpc-banked.inc; here we only add the payload bytes.
;; appmake +cpc --disk splits these into <MAIN>.b<n> disc files; z88dk loadbanks
;; streams them into the expansion RAM banks at boot.  DO NOT EDIT BY HAND.
;; ----------------------------------------------------------------------------
HEADER

if ( ! @banks ) {
    print $out "\n;; (no populated banks)\n";
} else {
    foreach my $b ( @banks ) {
        printf $out "\nSECTION BANK_%d\nBINARY \"%s\"   ;; %d bytes\n",
            $b->{'num'}, $b->{'path'}, $b->{'size'};
    }
}

close $out;

printf "bankscaffoldtool.pl: wrote %s (%d populated bank%s: %s)\n",
    $out_path,
    scalar( @banks ),
    ( @banks == 1 ? '' : 's' ),
    ( @banks ? join( ', ', map { "BANK_$_->{num}" } @banks ) : 'none' );
